"""empty message

Revision ID: 811fde7617de
Revises: ad2a42b22780
Create Date: 2020-04-14 08:30:41.288573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811fde7617de'
down_revision = 'ad2a42b22780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('reservation_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_reservation_reservation_time'), 'reservation', ['reservation_time'], unique=False)
    op.drop_index('ix_reservation_check_in', table_name='reservation')
    op.drop_column('reservation', 'check_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('check_in', sa.DATETIME(), nullable=True))
    op.create_index('ix_reservation_check_in', 'reservation', ['check_in'], unique=False)
    op.drop_index(op.f('ix_reservation_reservation_time'), table_name='reservation')
    op.drop_column('reservation', 'reservation_time')
    # ### end Alembic commands ###
