"""empty message

Revision ID: fc56e448a5d8
Revises: 811fde7617de
Create Date: 2020-04-14 09:38:56.341785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc56e448a5d8'
down_revision = '811fde7617de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('num_guests', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservation_num_guests'), 'reservation', ['num_guests'], unique=False)
    op.drop_column('reservation', 'check_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('check_in', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_reservation_num_guests'), table_name='reservation')
    op.drop_column('reservation', 'num_guests')
    # ### end Alembic commands ###
